# See: https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "asimov-keyring"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
#documentation.workspace = true
readme = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[package.metadata.readme]
title = "ASIMOV.rs: Keyring"

[features]
default = ["all", "std"]
std = ["asimov-core/std", "dep:whoami"]
unstable = []

# Features:
all = []

# Interoperability:
clap = ["dep:clap"]
serde = ["dep:serde"]
tracing = ["dep:tracing"]

[dependencies]
asimov-core.workspace = true
asimov-directory = { workspace = true, features = ["fs"] }
asimov-id = { workspace = true, features = ["iroh"] }
derive_more = { workspace = true, features = ["debug", "display", "from", "from_str"] }
iroh-base = { workspace = true, features = ["key"] }
keyring-core.workspace = true
secrecy.workspace = true
thiserror.workspace = true

# Features:

# Interoperability:
clap = { workspace = true, features = ["derive", "std"], optional = true }
serde = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
whoami = { workspace = true, features = ["std"], optional = true }

[target.'cfg(target_vendor = "apple")'.dependencies]
apple-native-keyring-store = { version = "1.0", features = ["keychain"] }

[target.'cfg(target_os = "windows")'.dependencies]
windows-native-keyring-store = "1.1"

[target.'cfg(target_os = "linux")'.dependencies]
linux-keyutils-keyring-store = "1.0"

# Preview locally with: RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
