# See: https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "asimov-runner"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
#documentation.workspace = true
readme = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[package.metadata.readme]
title = "ASIMOV.rs: Runner Implementation"

[features]
default = ["all", "std"]
all = ["tracing"]
std = ["asimov-core/std", "asimov-flow/tokio", "bytes/std", "clientele/std", "memchr/std", "tracing?/std"]
tracing = ["dep:tracing"]
unstable = []

[dependencies]
asimov-core.workspace = true
asimov-env = { workspace = true, default-features = true }
asimov-flow.workspace = true
asimov-module = { workspace = true, default-features = true }
asimov-patterns = { workspace = true, default-features = true }
asimov-prompt = { workspace = true, default-features = true }
async-stream.workspace = true
async-trait.workspace = true
bytes.workspace = true
clientele.workspace = true
derive_more = { workspace = true, features = ["debug"] }
futures-lite.workspace = true
memchr.workspace = true
tokio = { workspace = true, features = ["io-std", "io-util", "macros", "process", "rt", "sync", "time"] }
url.workspace = true

# Optional dependencies:
tracing = { workspace = true, optional = true }

[dev-dependencies]
serde_json = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["full", "test-util"] }

[[test]]
name = "pipeline"
path = "tests/pipeline.rs"
harness = false
required-features = ["std"]

# Preview locally with: RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
