// This is free and unencumbered software released into the public domain.

//! Ledger types for ASIMOV.
//!
//! This crate is a scaffold with a public but documentation-hidden ERC-20
//! contract binding generated by Alloy. It does not yet provide an ASIMOV ledger
//! model, transaction lifecycle, or persistence API.
//!
//! A first ledger integration needs an explicit provider and contract address,
//! token-unit conversion rules, and error handling for failed contract calls.
//! Those contracts remain to be defined and tested against a local provider.
//!
//! The crate uses `no_std`; its `std` feature forwards standard-library support
//! to `asimov-core` but does not add ledger functionality.

#![no_std]
#![forbid(unsafe_code)]
#![cfg_attr(docsrs, feature(doc_cfg))]

extern crate alloc;

#[cfg(feature = "std")]
extern crate std;

#[doc(hidden)]
pub mod contracts {
    pub mod erc20;
}
