# See: https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "asimov-flow"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
#documentation.workspace = true
readme = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories = ["concurrency", "network-programming", "no-std"]
publish = true

[package.metadata.readme]
title = "ASIMOV.rs: Flow Types"

[features]
default = ["all", "std"]
all = ["tokio"]
std = ["asimov-core/std", "async-flow/std", "bytes/std", "memchr/std"]
unstable = []

# Features:
tracing = []

# Integrations:
tokio = ["std", "dep:tokio"]

[dependencies]
asimov-core.workspace = true
async-flow.workspace = true
async-stream.workspace = true
bytes.workspace = true
futures-lite.workspace = true
memchr.workspace = true
#flows.workspace = true

# Integrations:
tokio = { workspace = true, features = ["io-util", "macros", "time"], optional = true }

[dev-dependencies]
futures-lite = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["rt", "test-util"] }

# Preview locally with: RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
